# List Comprehensions


In [ ]:
numbers = [1, 2, 3, 4,5]
mul = []
for elem in numbers:
    if elem < 4:
        mul.append(elem*2)
    
print(mul)

mul2 = [elem * 2 for elem in numbers if elem < 4]
print(mul2)



[2, 4, 6]
[2, 4, 6]


In [ ]:
numbers = [1, 2, 3, 4,5]
sub_numbers = numbers[-3:]
print(sub_numbers)

[3, 4, 5]


# NumPy creation, functions and slicing


In [10]:
import numpy as np
# help(np)

In [31]:
numbers_arr = np.array([1, 2, 3, 4,5, 6])
print(numbers_arr, type(numbers_arr))

ndim_arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9 , 0]], dtype='int32')
print(ndim_arr)

[1 2 3 4 5 6] <class 'numpy.ndarray'>
[[1 2 3 4 5]
 [6 7 8 9 0]]


In [ ]:
np.zeros((3, 3))

In [22]:
np.ones((3,3), dtype="int32")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
np.full((3, 3), 9.)

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

In [17]:
numbers_arr * 2

array([ 2,  4,  6,  8, 10])

In [30]:
# shape
print(ndim_arr.shape)

#ndim
print(ndim_arr.ndim)

# type
print(type(ndim_arr), ndim_arr.dtype)

# size
print(ndim_arr.nbytes)

(2, 5)
2
<class 'numpy.ndarray'> int32
40


In [32]:
lst = [2, 3, 4, 5, 6, 7]
np.array(lst).reshape(2,3)

array([[2, 3, 4],
       [5, 6, 7]])

In [40]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [43]:
a = np.arange(1, 10).reshape(3,3)
b = np.arange(11, 20).reshape(3, 3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [45]:
print(a * b)

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [46]:
np.matmul(a, b)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [49]:
a.std()

2.581988897471611

In [54]:
print(np.cos(30))
print(np.sin(180))

0.15425144988758405
-0.8011526357338304


In [57]:
# pointer
a = [1, 2, 3]
b = a
b[0] = 10
print(b, a)

a = np.array([1, 2, 3])
b = a.copy()
b[0] = 9
print(a, b)
# slicing

[10, 2, 3] [10, 2, 3]
[1 2 3] [9 2 3]


In [59]:
nums = np.arange(1, 10).reshape(3, 3)
nums

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(nums[1][1])
print(nums[1,1])
print(nums[1:, :2])

print(nums[:2, :2])
# 4, 5, 6, 7, 8 9
print(nums[1:, :])

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

5
5
[[4 5]
 [7 8]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]


# Skewness and kurtosis

# 3 Types of search Problems